import test from 'node:test';
import assert from 'node:assert/strict';
import { Scene,PerspectiveCamera,Vector3 } from 'three';
import { City } from '../src/world/City.js';
import { CollisionWorld } from '../src/world/CollisionWorld.js';
import { PlayerPhysics } from '../src/player/PlayerPhysics.js';
import { GrappleSystem } from '../src/player/GrappleSystem.js';
import { GameDirector } from '../src/gameplay/GameDirector.js';
import { DiscoverySystem } from '../src/systems/DiscoverySystem.js';
import { generateInteriors,selectAccessibleRoofs } from '../src/interiors/InteriorGenerator.js';
import { RoadNetwork } from '../src/utils/routes.js';
import { WorldPersistence } from '../src/save/WorldPersistence.js';
import { normalizeSettings } from '../src/save/SaveSchema.js';
import { ChunkStreamingManager } from '../src/world/ChunkStreamingManager.js';
import { SessionState } from '../src/systems/SessionState.js';

function fixture(){
  const scene=new Scene(),city=new City(scene),camera=new PerspectiveCamera(72);camera.position.set(0,1.75,54);city.collisionWorld=new CollisionWorld(city);
  const physics=new PlayerPhysics(camera,city.collisionWorld),player={physics,camera,keys:new Set(),wish:new Vector3(),controls:{pointerSpeed:.65,isLocked:true},resetInput(){this.keys.clear();},onAction(){}};
  const vertical={player,grapple:new GrappleSystem(camera,physics,[]),roofs:selectAccessibleRoofs(city),specs:generateInteriors(city),routes:{},discoveries:new DiscoverySystem([{id:'tower',x:32,y:157,z:-96}]),interiors:{active:null,enter(){}},underground:{active:false},interaction:{targets:[]},prompt:{},notify(){}};
  const living={scene,city,camera,vertical,rail:{stations:[]},performance:{level:'HIGH',profile:{}},rain:{enabled:true,intensity:1},traffic:{cars:[],count:0,network:new RoadNetwork(city)},audio:{}};
  living.gameplay=new GameDirector(living,player,undefined,{ui:false});living.city.streaming=new ChunkStreamingManager(city);
  const options={settings:normalizeSettings({}),capture(){return this.settings;},apply(s){this.settings=normalizeSettings(s);}};
  return {living,player,save:new WorldPersistence(living,player,options),options,dispose(){living.gameplay.dispose();city.streaming.dispose();city.dispose();}};
}
test('runtime resume restores actual physics, health, camera, vehicle and known discoveries',()=>{const f=fixture(),g=f.living.gameplay;g.setMode('VIGILANTE');f.living.camera.position.set(0,1.75,90);f.living.camera.rotation.set(.2,.4,0);g.health.hp=63;g.vehicles.vehicle.integrity=77;g.vehicles.vehicle.boost=31;f.living.vertical.discoveries.visited.add('tower');f.options.settings.cameraMotion=0;const saved=f.save.capture();f.save.reset();assert.equal(g.health.hp,100);assert.equal(f.save.restore(saved),true);assert.equal(g.mode,'VIGILANTE');assert.equal(g.health.hp,63);assert.deepEqual(f.living.camera.position.toArray(),saved.player.position);assert.equal(g.vehicles.vehicle.integrity,77);assert.equal(g.vehicles.vehicle.boost,31);assert.equal(f.options.settings.cameraMotion,0);assert.ok(f.living.vertical.discoveries.visited.has('tower'));f.dispose();});
test('resume in a building or below ground falls back to a validated safe point',()=>{const f=fixture(),saved=f.save.capture(),b=f.living.city.buildings[0];saved.player.position=[b.x,2,b.z];saved.safePoint.position=[0,1.75,100];assert.ok(f.save.restore(saved));assert.deepEqual(f.living.camera.position.toArray(),[0,1.75,100]);saved.player.position=[0,-10,30];saved.safePoint.position=[b.x,2,b.z];f.save.restore(saved);assert.deepEqual(f.living.camera.position.toArray(),[0,1.75,54]);f.dispose();});
test('invalid saved vehicle is recovered to deterministic garage and remains usable',()=>{const f=fixture(),s=f.save.capture(),b=f.living.city.buildings[0];s.vehicle.position=[b.x,0,b.z];s.vehicle.integrity=0;s.player.driving=true;f.save.restore(s);assert.deepEqual(f.living.gameplay.vehicles.vehicle.position.toArray(),[-7,0,32]);assert.equal(f.living.gameplay.vehicles.driving,true);assert.equal(f.living.gameplay.vehicles.vehicle.state,'DISABLED');assert.equal(f.living.gameplay.vehicles.exit(),true);f.dispose();});
test('safe driving resume restores camera mode and does not restore old velocity',()=>{const f=fixture(),s=f.save.capture();s.player.driving=true;s.vehicle.camera=2;f.save.restore(s);const v=f.living.gameplay.vehicles;assert.equal(v.driving,true);assert.equal(v.camera.mode,'HOOD');assert.equal(v.vehicle.speed,0);assert.equal(f.player.physics.frozen,true);assert.equal(f.player.controls.pointerSpeed,0);f.dispose();});
test('active foot mission rebuilds deterministic event and enemies without persisting AI',()=>{const f=fixture(),g=f.living.gameplay;g.setMode('VIGILANTE');const m=g.missions.missions[0];g.missions.activate(m.id);m.progress=1;const s=f.save.capture();assert.ok(s.activeMission);f.save.restore(s);assert.equal(g.missions.active.type,s.activeMission.type);assert.equal(g.missions.active.progress,1);assert.ok(g.enemies.enemies.length>0);assert.equal(g.crimes.events[0].site.id,s.activeMission.siteId);f.dispose();});
test('active vehicle mission resumes its seeded route and minimum progress',()=>{const f=fixture(),s=f.save.capture();s.mode='VIGILANTE';s.player.driving=true;s.activeVehicleMission={kind:'vehicle',type:'escort',serial:4,progress:3,remaining:90,distance:15};f.save.restore(s);const m=f.living.gameplay.vehicleMissions;assert.equal(m.active.type,'escort');assert.equal(m.serial,4);assert.equal(m.active.progress,3);assert.equal(m.active.remaining,90);assert.equal(m.agent.distance,15);f.dispose();});
test('new game resets exploration progression, missions and principal vehicle',()=>{const f=fixture(),g=f.living.gameplay;g.setMode('VIGILANTE');f.save.completedMissions.add('m');f.save.completedCrimes.add('c');f.living.vertical.discoveries.visited.add('tower');g.vehicles.vehicle.integrity=10;f.save.reset('EXPLORATION');assert.equal(g.crimes.events.length,0);assert.equal(g.enemies.enemies.length,0);assert.equal(f.save.completedMissions.size,0);assert.equal(f.living.vertical.discoveries.visited.size,0);assert.equal(g.vehicles.vehicle.integrity,100);f.dispose();});
test('paused shared clock leaves AI, player and vehicle unchanged then resumes without a jump',()=>{const f=fixture(),g=f.living.gameplay,s=new SessionState();g.setMode('VIGILANTE');s.play();s.delta(0);const before=f.save.capture(),enemy=g.enemies.enemies[0].position.clone();s.pause();for(let i=0;i<90;i++){const dt=s.delta(1/30);if(dt){g.update(dt);g.vehicles.update(dt);f.player.physics.update(dt,new Vector3(10,0,0));}}assert.deepEqual(f.save.capture().player,before.player);assert.deepEqual(f.save.capture().vehicle,before.vehicle);assert.ok(enemy.equals(g.enemies.enemies[0].position));s.play();assert.equal(s.delta(30),0);f.dispose();});
